package ogr.user12043.opencv.test.swing.gui;

import javax.swing.*;
import java.awt.image.BufferedImage;

/**
 * Created on 06.09.2018 - 10:15
 * part of opencv-test
 *
 * @author user12043
 */
public class CameraPanel extends javax.swing.JPanel {

    // Variables declaration - do not modify                     
    private javax.swing.JLabel jLabel_display;
    // End of variables declaration

    /**
     * Creates new form CameraPanel
     */
    public CameraPanel() {
        initComponents();
    }

    public void setImage(BufferedImage image) {
        jLabel_display.setIcon(new ImageIcon(image));
        revalidate();
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel_display = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        jLabel_display.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 2, true));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(jLabel_display, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents
}
